Document: dream
Title: Debian dream Manual
Author: <insert document author here>
Abstract: This manual describes what dream is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dream/dream.sgml.gz

Format: postscript
Files: /usr/share/doc/dream/dream.ps.gz

Format: text
Files: /usr/share/doc/dream/dream.text.gz

Format: HTML
Index: /usr/share/doc/dream/html/index.html
Files: /usr/share/doc/dream/html/*.html
